spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://192.168.200.138:3306/mall_pms?serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
  application:
    name: cloud-product
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置Nacos地址
#reids配置
#  redis:
#    host: 192.168.200.130
#    port: 6379
#    password:
#    timeout: 5000ms
#    expire: 400
#    connect-timeout: 5000ms
#    client-type: lettuce

mybatis-plus:
  global-config:
#    开启前缀扫描
    db-config:
      table-prefix: t_
#      开启id自增,关闭雪花算法
      id-type: auto